name: mlpoppyns
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - astropy=7.2.0
  - black=26.3.1
  - corner=2.2.3
  - dask=2026.3.0
  - dask-jobqueue=0.9.0
  - f2c=20210323183018
  - ffmpeg=8.0.1
  - graphviz=14.1.2
  - healpy=1.19.0
  - jupyterlab=4.5.6
  - matplotlib=3.10.9
  - notebook=7.5.5
  - numba=0.65.1
  - numpy=2.4.3
  - orjson=3.11.8
  - pandas=3.0.2
  - pip=26.0.1
  - pre-commit=4.6.0
  - pyinstrument=5.1.2
  - pytest=9.0.3
  - pytest-cov=7.1.0
  - pytest-runner=6.0.0
  - python=3.11.15
  - pytorch=2.4.0
  - pytorch-cuda=12.1  # Comment this out if you are a macOS user.
  - scipy=1.17.1
  - tensorboard=2.20.0
  - tensorboardx=2.6.2
  - termcolor=3.3.0
  - torchvision=0.19.0
  - pip:
      - pydeps
      - git+https://github.com/FRBs/pygedm.git@4.0.1
      - mkdocs-material
      - mkdocstrings-python
      - python-markdown-math
      - harmonic