"""
    Generator for a single simulation.

    This module creates a dataset of compressed representations for the output of
    a single simulated populations from the simulator `simulate_population_magrot_det.py`
    where the following initial parameters were modified:  B_initial_log10_mean`,
    `B_initial_log10_sigma`, `P_initial_log10_mean`, `P_initial_log10_sigma`, `a_late`,
    `L_radio_log10_mean`, `epsilon_L`, h_c, sigma_k.

    These compressed representations will encode both the dynamical properties,
    the magneto-rotational properties and the fluxes of detected synthetic pulsars.

    The user can choose to generate either a dataset of images or of 2D arrays.

    The information on the simulated dataset is also saved in a .csv file where the
    corresponding input files are specified with their paths and labels.


    Display help message to run the code:

    python generate_single_surveys.py --help

    Displays all the relevant arguments that can be used.

    Authors:

        Michele Ronchi (ronchi@ice.csic.es)
        Celsa Pardo Araujo  (pardo@ice.csic.es)
"""

import argparse
import json
import logging
import pathlib
import sys
from pathlib import Path

import numpy as np
import pandas as pd

import mlpoppyns.generator.maps.position_maps as pmaps
import mlpoppyns.generator.maps.ppdot_fluxes_map as ppdfmaps
import mlpoppyns.generator.maps.ppdot_maps as ppdmaps
import mlpoppyns.generator.maps.velocity_maps as vmaps
from mlpoppyns.simulator.config_simulator import cfg

log = logging.getLogger(__name__)


def create_survey_maps(
    simulation_output_path: Path,
    dataset_path: str,
    survey_name: str,
    survey_filename: str,
    data_type: str,
    resolution_dyn: int,
    resolution_ppdot: int,
    dictionary_position_map_radec: dict,
    dictionary_velocity_map_vra: dict,
    dictionary_velocity_map_vdec: dict,
    dictionary_ppdot_map: dict,
    dictionary_ppdot_flux_map: dict,
) -> None:
    """
    This method reads the simulated survey files of a given simulation (usually generated by the simulation helper)
    and generates a set of density maps in the specified format (images or arrays) and with a specified resolution.

    Args:
        simulation_output_path (str): Path to where the simulated populations are located.
        dataset_path (str): Path to where the generated dataset will be saved.
        survey_name (str): Survey acronym.
        survey_filename (str): Survey filename.
        data_type (str): Type of dataset to generate: array or image.
        resolution_dyn (int): Resolution (number of bins per axis for the 2d
            histograms) for the position and velocity maps to generate. In case of RA DEC maps the
            DEC axis has half the number of bins with respect to the RA axis.
        resolution_ppdot (int): Resolution (number of bins per axis for the 2d
            histograms) for the P-Pdot density maps to generate.
        dictionary_position_map_radec (dict): Dictionary containing the path to the position maps in RA, DEC for
            all the simulated surveys.
        dictionary_velocity_map_vra (dict): Dictionary containing the path to the proper motion maps in RA for
            all the simulated surveys.
        dictionary_velocity_map_vdec (dict): Dictionary containing the path to the proper motion maps in DEC for
            all the simulated surveys.
        dictionary_ppdot_map (dict): Dictionary containing the path to the P-Pdot maps for
            all the simulated surveys.
        dictionary_ppdot_flux_map (dict): Dictionary containing the path to the averaged flux P-Pdot maps for
            all the simulated surveys.
    """

    # Check if the simulated survey file exists as a precondition.
    survey_path = pathlib.Path(
        f"{simulation_output_path}/{survey_filename}.pkl.gz"
    )

    if not survey_path.exists():
        log.error(f"Survey output file not found in {survey_path}")
        sys.exit()

    # Create a dataframe object from the .pkl population file.
    df_survey = pd.read_pickle(str(survey_path), compression="gzip")

    # Remove the units header row from the dataframe.
    df_survey.columns = [x[0] for x in df_survey.columns]

    # We set the sample_number equal to 0 since there is just one simulation.
    sample_number = 0

    # Create position density maps projected onto the RA DEC plane.
    pmaps.generate_position_map(
        dataset_path,
        f"survey_{survey_name}_position_map_radec",
        sample_number,
        data_type,
        df_survey["ra"],
        df_survey["dec"],
        resolution_dyn,
        int(resolution_dyn / 2),
        dictionary_position_map_radec,
        x_limits=(0.0, 360.0),
        y_limits=(-90.0, 90.0),
    )

    # Create velocity maps of component v_RA in the RA DEC plane.
    vmaps.generate_velocity_map(
        dataset_path,
        f"survey_{survey_name}_velocity_map_vra",
        sample_number,
        data_type,
        df_survey["ra"],
        df_survey["dec"],
        abs(df_survey["pm_ra"]),
        resolution_dyn,
        int(resolution_dyn / 2),
        dictionary_velocity_map_vra,
        x_limits=(0.0, 360.0),
        y_limits=(-90.0, 90.0),
    )

    # Create velocity maps of component v_DEC in the RA DEC plane.
    vmaps.generate_velocity_map(
        dataset_path,
        f"survey_{survey_name}_velocity_map_vdec",
        sample_number,
        data_type,
        df_survey["ra"],
        df_survey["dec"],
        abs(df_survey["pm_dec"]),
        resolution_dyn,
        int(resolution_dyn / 2),
        dictionary_velocity_map_vdec,
        x_limits=(0.0, 360.0),
        y_limits=(-90.0, 90.0),
    )

    # Create P-Pdot density maps.
    ppdmaps.generate_ppdot_map(
        dataset_path,
        f"survey_{survey_name}_ppdot_map",
        sample_number,
        data_type,
        df_survey["P"],
        df_survey["P_dot"],
        resolution_ppdot,
        resolution_ppdot,
        dictionary_ppdot_map,
    )

    # Since the TPA program on Meerkat is not complete, we will take a random subsample of the PMPS, SMPS, and HTRU
    # surveys that match the numbers in the TPA program, ensuring there is no bias in this subsample.
    if int(cfg[f"detected_meerkat_{survey_name}"]) < len(df_survey["P"]):
        df_survey = df_survey.sample(
            n=int(cfg[f"detected_meerkat_{survey_name}"])
        )

    ppdfmaps.generate_ppdot_fluxes_map(
        dataset_path,
        f"survey_{survey_name}_ppdot_map_fluxes",
        sample_number,
        data_type,
        df_survey["P"],
        df_survey["P_dot"],
        np.log10(df_survey["S_radio_obs_mean_1400"]),
        resolution_ppdot,
        resolution_ppdot,
        dictionary_ppdot_flux_map,
        x_limits=(1e-3, 1e2),
        y_limits=(1e-21, 1e-9),
    )


def generate_dataset(args: argparse.Namespace) -> None:
    """
    This method generates a dataset of density maps in the specified format (images or arrays) and with a specified
    resolution from a set of simulated populations (usually generated by the simulation helper).
    All the information about the dataset is stored in a dataset.csv file containing the density-map file names
    and the set of parameter values for each simulated population.

    Args:
        args (argparse.Namespace): An argparse.Namespace object containing the following attributes:

            - data (str): Path to where the simulated populations are located.
            - save_dir (str): Path to where the generated dataset will be saved.
            - data_type (str): Type of dataset to generate: array or image.
            - resolution_dyn (int): Resolution (number of bins per axis for the 2d
                histograms) for the position and velocity maps to generate. In case of RA DEC maps the
                DEC axis has half the number of bins with respect to the RA axis.
            - resolution_ppdot (int): Resolution (number of bins per axis for the 2d
                histograms) for the P-Pdot density maps to generate.
    """

    # Create the dataset directory path.
    dataset_path = f"{args.save_dir}"
    pathlib.Path(dataset_path).mkdir(parents=True, exist_ok=True)

    # Initialize dictionaries that will contain the density-map file names and
    # the corresponding set of parameter values.
    survey_PMPS_position_map_radec_dictionary = {}
    survey_PMPS_velocity_map_vra_dictionary = {}
    survey_PMPS_velocity_map_vdec_dictionary = {}
    survey_PMPS_ppdot_map_dictionary = {}
    survey_PMPS_ppdot_fluxes_map_dictionary = {}

    survey_SMPS_position_map_radec_dictionary = {}
    survey_SMPS_velocity_map_vra_dictionary = {}
    survey_SMPS_velocity_map_vdec_dictionary = {}
    survey_SMPS_ppdot_map_dictionary = {}
    survey_SMPS_ppdot_fluxes_map_dictionary = {}

    survey_HTRU_position_map_radec_dictionary = {}
    survey_HTRU_velocity_map_vra_dictionary = {}
    survey_HTRU_velocity_map_vdec_dictionary = {}
    survey_HTRU_ppdot_map_dictionary = {}
    survey_HTRU_ppdot_fluxes_map_dictionary = {}

    param_dictionary = {}

    # Check if the parsed simulated population directory exists.
    root_path = pathlib.Path(args.data)
    if not root_path.exists():
        log.error(f"Directory {root_path} not found...")
        sys.exit()

    log.info("Generating sample...")

    # Create a set of maps for each survey.
    create_survey_maps(
        root_path,
        dataset_path,
        "PMPS",
        "survey_PMPS_results",
        args.data_type,
        args.resolution_dyn,
        args.resolution_ppdot,
        survey_PMPS_position_map_radec_dictionary,
        survey_PMPS_velocity_map_vra_dictionary,
        survey_PMPS_velocity_map_vdec_dictionary,
        survey_PMPS_ppdot_map_dictionary,
        survey_PMPS_ppdot_fluxes_map_dictionary,
    )

    create_survey_maps(
        root_path,
        dataset_path,
        "SMPS",
        "survey_SMPS_results",
        args.data_type,
        args.resolution_dyn,
        args.resolution_ppdot,
        survey_SMPS_position_map_radec_dictionary,
        survey_SMPS_velocity_map_vra_dictionary,
        survey_SMPS_velocity_map_vdec_dictionary,
        survey_SMPS_ppdot_map_dictionary,
        survey_SMPS_ppdot_fluxes_map_dictionary,
    )

    create_survey_maps(
        root_path,
        dataset_path,
        "HTRU",
        "survey_HTRU_low_mid_results",
        args.data_type,
        args.resolution_dyn,
        args.resolution_ppdot,
        survey_HTRU_position_map_radec_dictionary,
        survey_HTRU_velocity_map_vra_dictionary,
        survey_HTRU_velocity_map_vdec_dictionary,
        survey_HTRU_ppdot_map_dictionary,
        survey_HTRU_ppdot_fluxes_map_dictionary,
    )

    # Check if files containing labels exists as a precondition.
    label_path = pathlib.Path(f"{root_path}/override.json")

    if not label_path.exists():
        config_json = json.load(
            open(
                pathlib.Path().joinpath(root_path, "configuration.json"),
            )
        )
        # If the override.json is not found we save the parameter values from the configuration.json file as a
        # dictionary.
        param_dictionary.update(
            {
                "B_initial_log10_mean": config_json["B_initial_log10_mean"],
                "B_initial_log10_sigma": config_json["B_initial_log10_sigma"],
                "P_initial_log10_mean": config_json["P_initial_log10_mean"],
                "P_initial_log10_sigma": config_json["P_initial_log10_sigma"],
                "a_late": config_json["a_late"],
                "L_radio_log10_mean": config_json["L_radio_log10_mean"],
                "epsilon_L": config_json["epsilon_L"],
                "h_c": config_json["h_c"],
                "sigma_k": config_json["sigma_k"],
            }
        )
    else:
        # Save the parameter values as a dictionary.
        with open(label_path) as file:
            dictionary = json.load(file)
            for key, val in dictionary.items():
                param_dictionary.setdefault(key, []).append(val)

    # Merge the filename and parameter dictionaries into a single dictionary.
    dataset_dictionary = {
        **survey_PMPS_position_map_radec_dictionary,
        **survey_SMPS_position_map_radec_dictionary,
        **survey_HTRU_position_map_radec_dictionary,
        **survey_PMPS_velocity_map_vra_dictionary,
        **survey_SMPS_velocity_map_vra_dictionary,
        **survey_HTRU_velocity_map_vra_dictionary,
        **survey_PMPS_velocity_map_vdec_dictionary,
        **survey_SMPS_velocity_map_vdec_dictionary,
        **survey_HTRU_velocity_map_vdec_dictionary,
        **survey_PMPS_ppdot_map_dictionary,
        **survey_SMPS_ppdot_map_dictionary,
        **survey_HTRU_ppdot_map_dictionary,
        **survey_PMPS_ppdot_fluxes_map_dictionary,
        **survey_SMPS_ppdot_fluxes_map_dictionary,
        **survey_HTRU_ppdot_fluxes_map_dictionary,
        **param_dictionary,
    }

    # Write the whole dataset dictionary into a .csv file.
    dataset_filename = f"{dataset_path}/dataset_full.csv"

    df = pd.DataFrame(
        {key: pd.Series(value) for key, value in dataset_dictionary.items()}
    )
    df.to_csv(dataset_filename, encoding="utf-8", index=False)

    log.info("File dataset_full.csv generated")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Parameters")
    parser.add_argument(
        "--data",
        nargs="?",
        type=str,
        required=True,
        help="Path to where the simulated population is located.",
    )
    parser.add_argument(
        "--save_dir",
        nargs="?",
        type=str,
        default="output/gen_single",
        help="Path to the folder, where the dataset will be saved.",
    )
    parser.add_argument(
        "--data_type",
        nargs="?",
        type=str,
        choices=["array", "image"],
        default="array",
        help="Type of dataset to generate: array or image.",
    )
    parser.add_argument(
        "--resolution_dyn",
        nargs="?",
        type=int,
        default=64,
        help="Resolution of the position and velocity maps that will be generated (in number of bins).",
    )
    parser.add_argument(
        "--resolution_ppdot",
        nargs="?",
        type=int,
        default=64,
        help="Resolution of the P-Pdot maps that will be generated (in number of bins).",
    )

    args = parser.parse_args()

    logging.basicConfig(stream=sys.stdout, level=logging.INFO)

    generate_dataset(args)
