# Overall name of workflow.
name: Github Action Pipeline
# Point of execution: we execute the action at each push.
on: push
# Individual jobs to run; note multiple jobs will be run in parallel.
jobs:
  # Unique job ID.
  job_test:
    # Name of job
    name: Run tests
    # Operating system that is being used.
    runs-on: ubuntu-latest
    # Specify defaults: we run commands on a bash shell.
    # This ensures that conda can be activated.
    defaults:
      run:
        shell: bash -el {0}
    # Specify permissions to access code in repository.
    permissions:
      contents: read
    # Specific steps to be executed for `Run tests` job.
    steps:
      # Free up disk space to avoid action failing.
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      # Check out the full code given in the repo.
      - name: Checkout code
        uses: actions/checkout@v4
      # Setup miniconda and create the (empty) environment.
      # Note: this does not install any packages yet but activates the environment.
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mlpoppyns
      # As it takes about 5min to generate the full environment for each run,
      # we cache it after first creation and subsequently restore it to avoid recreation at every push.
      # We also use the hash of the corresponding environment file for the key to check environment modifications below.
      - name: Caching environment
        uses: actions/cache@v4
        with:
          path: /usr/share/miniconda/envs/mlpoppyns
          key: conda-${{ hashFiles('environment.yaml') }}
        id: cache
      # Create full environment if key from previous step does not match a key stored in the cache.
      # E.g., if environment.yaml has been modified, keys won't match and the full environment is recreated.
      # We use the --yes attribute to recreate the environment with the same name.
      - name: Create environment
        run: conda env create --file environment.yaml --yes
        if: steps.cache.outputs.cache-hit != 'true'
      # As the pip dependencies are not installed in /usr/share/miniconda/envs/pop_syn
      # and therefore not cached, we update the environment every time to add pip dependencies.
      - name: Install pip dependencies
        run: conda env update -n mlpoppyns --file environment.yaml
      # Install our software package in the standard way.
      - name: Install package in development mode
        run: python setup.py develop
      # Install specific version of sbi via pip.
      - name: Install sbi package from pip
        run: pip install sbi==0.22.0
      # Run all the relevant tests using pytest.
      - name: Run tests
        run: pytest